### ISSUE TITLE
Add button to settings allowing a reset of the webhook

### ISSUE THREAD

**Issue by ketra** [ketra/nl.ketra.point#36]
related to #35 
Add button to settings allowing a reset of the webhook this so a user can reset the webhook.

**Comment by ketra** [comment]
New settings page created, including:
- logging 
- the registered hooks.
- a refresh hooks button.

**Comment by MP-ICT-Diensten** [comment]
Delete the old hooks from minut account.

**Comment by MP-ICT-Diensten** [comment]
Works (I think)

**Comment by ketra** [comment]
Fixed in V2
