### ISSUE TITLE
Better readme

### ISSUE THREAD

**Issue by ketra** [ketra/nl.ketra.point#46]
Homey has refused the review to push the app to production, a better readme should be supplied.

**Comment by ketra** [comment]
@MP-ICT-Diensten kan jij een mooi verhaaltje schrijven voor de app store. en toevoegen aan deze ticket (miss zowel engels als nederlands)

**Comment by MP-ICT-Diensten** [comment]
Ga ik doen.

**Comment by MP-ICT-Diensten** [comment]
Readme updated and also an NL version created (GT and some manual editing).
Created pull request for files.
