### ISSUE TITLE
Is a Minut subscription needed?

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [ketra/nl.ketra.point#48]
If I look a the website of Minut the say you need a Minut Pro subscription to use the API.
https://support.minut.com/en/articles/1653265-api-connection-and-documentation

I myself have only a Minut Standard subscription and everything works using the API.
@ketra do you have a subscription?

Subscription prices: https://www.minut.com/store/

Or is Homey integration subscription free for now?

**Comment by ketra** [comment]
I dont have a subscription, hope this wont affect current integrations. If this will affect it we need to look for a solution at that moment.

**Comment by ketra** [comment]
Does not seem like it.
