### ISSUE TITLE
Minut test app 2.x, no value updates

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [ketra/nl.ketra.point#55]
I have touched the Minuts to charge battery, result is that the motion alarm is not going off anymore and all sensor values like temp and hum are not updated in the last 24h. ( last updated one day ago).

diag of app with wrong values: 6e226edb-d05f-4a05-b1d1-abd438618b53
Diag after restart app on homey: 92c67fff-21ba-44ea-b474-358e64067dad

**Comment by MP-ICT-Diensten** [comment]
After 22 hours, I looked and I noticed that from the 4 measured values (temp, hum, pressure, sound), only pressure is not updated (luchtdruk), the other 2 are.

In the device activity in Homey I only see Movement detected On/Off  and no Humidity Alarm On/Off, while I know this one has been detected this morning on MInut App on phone.

In InfluxDB stats no alarm_motion or alarm_noise are registered, fields do exist after alarm has happened. (Probably this is a  boolean and not exported by InfluxDB exporter app).

**Comment by MP-ICT-Diensten** [comment]
Pressure is always 1012.22 mbar  and not updated after Minut app restart on Homey. It doe say that value is updated in Homey device, but the number is the same as previous.

**Comment by ketra** [comment]
Looking at the Point device this is also the case at my side. however, when investigating it looks like the values received from the API are not updating. So this looks like an issue at the side of Minut itself

**Comment by MP-ICT-Diensten** [comment]
Strange, battery status of one of the minuts is not updated every hour, one updates every hour and the other does not report anything anymore.

**Comment by MP-ICT-Diensten** [comment]
Solved
