### ISSUE TITLE
Cannot login with Minut Account

### ISSUE THREAD

**Issue by rolu01** [ketra/nl.ketra.point#65]
I am trying to add Minut app to my Homey but get the following error when I am trying to configure and login:

```
{
"message": "This client is not owned by the authenticated user",
"error_key": "client_restricted_to_owner"
}
```

**Comment by ruudsolidnl** [comment]
Same here. Please advice. I can login to your site directly and have full access to the point via the Minute app.

**Comment by ketra** [comment]
Minut has put the API behind a paywall, therefor i cannot test/develop the app any further. I have had contact with Minut as well as with Athom. No cooperation was possible to allow me to develop the app any further. Therefor this app is no longer developed and integration with the homey has become impossible.
